### ISSUE TITLE
Invoice gets through with no taxes when an issue occurs on the client

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill-avatax-plugin#3]
When for some reason an issue occurs and the client can't get a response from the Avalara API, the invoice is still allowed to be created, which makes it potentially broken: the invoice might need some taxes, but has none.

This is highly critical since the invoice is getting processed anyway, a payment is made. It might happen that we make a user pay an invoice with missing taxes!

An example stack-trace (here for a dry-run invoice):
```
2017-05-30T10:58:38,854+0000 lvl='WARN', log='AvaTaxTaxCalculatorBase', th='catalina-exec-3', xff='', rId='1e5a3241-baff-4769-84ec-ec76c9a124c5', aRId='1', tRId='1', Unable to compute tax for account 0232e649-2a10-4032-bfdc-9d329fafabb2
org.killbill.billing.plugin.avatax.client.AvaTaxClientException: java.util.concurrent.ExecutionException: java.net.ConnectException: http://172.17.0.1.xip.io:80
        at org.killbill.billing.plugin.avatax.client.AvaTaxClient.getTax(AvaTaxClient.java:123)
        at org.killbill.billing.plugin.avatax.api.AvaTaxTaxCalculator.buildInvoiceItems(AvaTaxTaxCalculator.java:97)
        at org.killbill.billing.plugin.avatax.api.AvaTaxTaxCalculatorBase.getTax(AvaTaxTaxCalculatorBase.java:125)
        at org.killbill.billing.plugin.avatax.api.AvaTaxTaxCalculatorBase.compute(AvaTaxTaxCalculatorBase.java:85)
        at org.killbill.billing.plugin.api.invoice.PluginInvoicePluginApi.getAdditionalTaxInvoiceItems(PluginInvoicePluginApi.java:136)
        at org.killbill.billing.plugin.api.invoice.PluginInvoicePluginApi.getAdditionalTaxInvoiceItems(PluginInvoicePluginApi.java:83)
        at org.killbill.billing.plugin.avatax.api.AvaTaxInvoicePluginApi.getAdditionalInvoiceItems(AvaTaxInvoicePluginApi.java:75)
        at org.killbill.billing.plugin.avatax.api.AvalaraInvoicePluginApi.getAdditionalInvoiceItems(AvalaraInvoicePluginApi.java:82)
        at sun.reflect.GeneratedMethodAccessor453.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler$1.execute(ContextClassLoaderHelper.java:144)
        at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
        at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler.handleInvocation(ContextClassLoaderHelper.java:141)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
        at com.sun.proxy.$Proxy241.getAdditionalInvoiceItems(Unknown Source)
        at org.killbill.billing.invoice.InvoicePluginDispatcher.getAdditionalInvoiceItems(InvoicePluginDispatcher.java:68)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:421)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:288)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:251)
        at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi.triggerInvoiceGeneration(DefaultInvoiceUserApi.java:217)
        at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi$$EnhancerByGuice$$1c4ddc95.CGLIB$triggerInvoiceGeneration$21(<generated>)
        at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi$$EnhancerByGuice$$1c4ddc95$$FastClassByGuice$$51d1ae58.invoke(<generated>)
        at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
        at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:52)
        at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
        at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:49)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
        at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
        at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
        at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
        at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
        at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi$$EnhancerByGuice$$1c4ddc95.triggerInvoiceGeneration(<generated>)
        at org.killbill.billing.jaxrs.resources.InvoiceResource.generateDryRunInvoice(InvoiceResource.java:399)
[...]
```

In this example, I'm using a fake Avalara API url to simulate a connectivity issue. Such a issue might not happen often in a real use-case, but still could (Avalara down for maintenance, some routing down, ...), and if it happens, it would be really bad.

Best thing would be to fail the invoice creation when it is impossible to get a tax result (ie. when it is impossible to guarantee that the invoice indeed needs no taxes).

**Comment by pierre** [comment]
> Best thing would be to fail the invoice creation when it is impossible to get a tax result (ie. when it is impossible to guarantee that the invoice indeed needs no taxes).

This could probably easily be done by simply propagating the exceptions to Kill Bill, see https://github.com/killbill/killbill-avatax-plugin/blob/7e059c07da9a4352ff982288c2b3e72fd072906c/src/main/java/org/killbill/billing/plugin/avatax/api/AvaTaxTaxCalculatorBase.java#L126-L135.

That being said, this behavior should be configurable. As described [here](https://developer.avalara.com/avatax/errors-and-outages/), outages can be dealt in different ways depending on the e-commerce use-case (e.g. you might not want to prevent invoice generation just because a third-party service is down, even if you need to absorb the costs down the line).

**Comment by GregOriol** [comment]
I'm not sure about "easily": tried that, but got a subscription change validated, with no invoice :-/

**Comment by pierre** [comment]
This behavior is expected: the subscription and [invoice](http://docs.killbill.io/latest/invoice_subsystem.html) subsystems are independent. While the subscription change goes through, the invoice is not generated and the account goes into [overdue](http://docs.killbill.io/latest/overdue.html).

**Comment by pierre** [comment]
This was fixed as part of https://github.com/killbill/killbill-avatax-plugin/pull/17.
